

*   Name: Cagdas Bugra Altindal
*   Student ID: 20014643
*   Date: 20/12/2023
*   About CA_2: Generalized Linear Model(GLM), Time Series Analysis, Bayesian Analytics










# PRE-PROCESSING

In [1]:
df <- read.csv("shopping_trends_updated.csv")
head(df)

CUSTOMER.ID AGE GENDER ITEM.PURCHASED CATEGORY PURCHASE.AMOUNT LOCATION     
1 1           55  Male   Blouse         Clothing 53              Kentucky     
2 2           19  Male   Sweater        Clothing 64              Maine        
3 3           50  Male   Jeans          Clothing 73              Massachusetts
4 4           21  Male   Sandals        Footwear 90              Rhode Island 
5 5           45  Male   Blouse         Clothing 49              Oregon       
6 6           46  Male   Sneakers       Footwear 20              Wyoming      
  SIZE COLOR     SEASON REVIEW.RATE SUBSCRIPTIONS SHIPPING.TYPE
1 L    Gray      Winter 3.1         Yes           Express      
2 L    Maroon    Winter 3.1         Yes           Express      
3 S    Maroon    Spring 3.1         Yes           Free Shipping
4 M    Maroon    Spring 3.5         Yes           Next Day Air 
5 M    Turquoise Spring 2.7         Yes           Free Shipping
6 M    White     Summer 2.9         Yes           Standard     
  DISCOUNT.APPLIED PROMO_CODE_USED PREVIOUS.PURCHASES PAYMENT.METHOD
1 Yes              Yes             14                 Venmo         
2 Yes              Yes              2                 Cash          
3 Yes              Yes             23                 Credit Card   
4 Yes              Yes             49                 PayPal        
5 Yes              Yes             31                 PayPal        
6 Yes              Yes             14                 Venmo         
  FREQUENCY.OF.PURCHASES
1 Fortnightly           
2 Fortnightly           
3 Weekly                
4 Weekly                
5 Annually              
6 Weekly

In [2]:
# CHECKING MISSING VALUES FOR EACH FEATURE DATA FRAME
missing_values <- colSums(is.na(df))
missing_values

CUSTOMER.ID                    AGE                 GENDER 
                     0                      0                      0 
        ITEM.PURCHASED               CATEGORY        PURCHASE.AMOUNT 
                     0                      0                      0 
              LOCATION                   SIZE                  COLOR 
                     0                      0                      0 
                SEASON            REVIEW.RATE          SUBSCRIPTIONS 
                     0                      0                      0 
         SHIPPING.TYPE       DISCOUNT.APPLIED        PROMO_CODE_USED 
                     0                      0                      0 
    PREVIOUS.PURCHASES         PAYMENT.METHOD FREQUENCY.OF.PURCHASES 
                     0                      0                      0

In [3]:
# REMOVING DUPLICATED ROWS
unique_df <- unique(df)
df <- unique_df
head(df)

CUSTOMER.ID AGE GENDER ITEM.PURCHASED CATEGORY PURCHASE.AMOUNT LOCATION     
1 1           55  Male   Blouse         Clothing 53              Kentucky     
2 2           19  Male   Sweater        Clothing 64              Maine        
3 3           50  Male   Jeans          Clothing 73              Massachusetts
4 4           21  Male   Sandals        Footwear 90              Rhode Island 
5 5           45  Male   Blouse         Clothing 49              Oregon       
6 6           46  Male   Sneakers       Footwear 20              Wyoming      
  SIZE COLOR     SEASON REVIEW.RATE SUBSCRIPTIONS SHIPPING.TYPE
1 L    Gray      Winter 3.1         Yes           Express      
2 L    Maroon    Winter 3.1         Yes           Express      
3 S    Maroon    Spring 3.1         Yes           Free Shipping
4 M    Maroon    Spring 3.5         Yes           Next Day Air 
5 M    Turquoise Spring 2.7         Yes           Free Shipping
6 M    White     Summer 2.9         Yes           Standard     
  DISCOUNT.APPLIED PROMO_CODE_USED PREVIOUS.PURCHASES PAYMENT.METHOD
1 Yes              Yes             14                 Venmo         
2 Yes              Yes              2                 Cash          
3 Yes              Yes             23                 Credit Card   
4 Yes              Yes             49                 PayPal        
5 Yes              Yes             31                 PayPal        
6 Yes              Yes             14                 Venmo         
  FREQUENCY.OF.PURCHASES
1 Fortnightly           
2 Fortnightly           
3 Weekly                
4 Weekly                
5 Annually              
6 Weekly

CHANGE STRINGS TO NUMERIC

In [4]:
createNumericMapping <- function(column) {
  unique_values <- unique(column)
  if (length(unique_values) > 0) {
    mapping <- setNames(0:(length(unique_values) - 1), unique_values)
    return(mapping[column])
  } else {
    return(column)
  }
}

# Apply the function to each relevant column
df$GENDER <- createNumericMapping(df$GENDER)
unique(df$GENDER)

df$ITEM.PURCHASED <- createNumericMapping(df$ITEM.PURCHASED)
unique(df$ITEM.PURCHASED)

df$CATEGORY <- createNumericMapping(df$CATEGORY)
unique(df$CATEGORY)

df$LOCATION <- createNumericMapping(df$LOCATION)
unique(df$LOCATION)

df$SIZE <- createNumericMapping(df$SIZE)
unique(df$SIZE)

df$COLOR <- createNumericMapping(df$COLOR)
unique(df$COLOR)

df$SEASON <- createNumericMapping(df$SEASON)
unique(df$SEASON)

df$SUBSCRIPTIONS <- createNumericMapping(df$SUBSCRIPTIONS)
unique(df$SUBSCRIPTIONS)

df$SHIPPING.TYPE <- createNumericMapping(df$SHIPPING.TYPE)
unique(df$SHIPPING.TYPE)

df$DISCOUNT.APPLIED <- createNumericMapping(df$DISCOUNT.APPLIED)
unique(df$DISCOUNT.APPLIED)

x <- createNumericMapping(df$PROMO_CODE_USED)
df$PROMO_CODE_USED <- x
unique(df$PROMO_CODE_USED)

df$PAYMENT.METHOD <- createNumericMapping(df$PAYMENT.METHOD)
unique(df$PAYMENT.METHOD)

df$FREQUENCY.OF.PURCHASES <- createNumericMapping(df$FREQUENCY.OF.PURCHASES)
unique(df$FREQUENCY.OF.PURCHASES)

[1] 0 1

[1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

[1] 0 1 2 3

[1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
[26] 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49

[1] 0 1 2 3

[1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

[1] 0 1 2 3

[1] 0 1

[1] 0 1 2 3 4 5

[1] 0 1

[1] 0 1

[1] 0 1 2 3 4 5

[1] 0 1 2 3 4 5 6

In [5]:
head(df)

CUSTOMER.ID AGE GENDER ITEM.PURCHASED CATEGORY PURCHASE.AMOUNT LOCATION SIZE
1 1           55  0      0              0        53              0        0   
2 2           19  0      1              0        64              1        0   
3 3           50  0      2              0        73              2        1   
4 4           21  0      3              1        90              3        2   
5 5           45  0      0              0        49              4        2   
6 6           46  0      4              1        20              5        2   
  COLOR SEASON REVIEW.RATE SUBSCRIPTIONS SHIPPING.TYPE DISCOUNT.APPLIED
1 0     0      3.1         0             0             0               
2 1     0      3.1         0             0             0               
3 1     1      3.1         0             1             0               
4 1     1      3.5         0             2             0               
5 2     1      2.7         0             1             0               
6 3     2      2.9         0             3             0               
  PROMO_CODE_USED PREVIOUS.PURCHASES PAYMENT.METHOD FREQUENCY.OF.PURCHASES
1 0               14                 0              0                     
2 0                2                 1              0                     
3 0               23                 2              1                     
4 0               49                 3              1                     
5 0               31                 3              2                     
6 0               14                 0              1

In [6]:
# Display correlation matrix
cor_matrix <- cor(df)
cor_matrix

CUSTOMER.ID  AGE          GENDER       ITEM.PURCHASED
CUSTOMER.ID             1.000000000 -0.004078574  0.807960422 -0.003119671  
AGE                    -0.004078574  1.000000000 -0.002763261  0.003797920  
GENDER                  0.807960422 -0.002763261  1.000000000 -0.009858613  
ITEM.PURCHASED         -0.003119671  0.003797920 -0.009858613  1.000000000  
CATEGORY               -0.007119867  0.012336349 -0.005205720  0.493024184  
PURCHASE.AMOUNT         0.011047801 -0.010423647  0.014044098  0.014553589  
LOCATION                0.025650602  0.002397486  0.016179818  0.022297922  
SIZE                    0.019584815 -0.021007726  0.011982914  0.011719635  
COLOR                   0.010546516 -0.019860983  0.006721157  0.017113237  
SEASON                  0.013730841  0.019300493  0.014328538  0.019270203  
REVIEW.RATE             0.001343012 -0.021949148 -0.008163790  0.030357957  
SUBSCRIPTIONS           0.768960362 -0.006491647  0.417196816  0.002254828  
SHIPPING.TYPE          -0.002565024 -0.022290602 -0.010669697  0.005042345  
DISCOUNT.APPLIED        0.857496384 -0.004366296  0.595823095 -0.007766058  
PROMO_CODE_USED         0.857496384 -0.004366296  0.595823095 -0.007766058  
PREVIOUS.PURCHASES     -0.039158526  0.040444531 -0.035872605  0.005103386  
PAYMENT.METHOD         -0.010510315  0.001963116 -0.018432871  0.009739294  
FREQUENCY.OF.PURCHASES  0.018919373 -0.013304658  0.015580428  0.001377600  
                       CATEGORY     PURCHASE.AMOUNT LOCATION     SIZE        
CUSTOMER.ID            -0.007119867  0.011047801     0.025650602  0.019584815
AGE                     0.012336349 -0.010423647     0.002397486 -0.021007726
GENDER                 -0.005205720  0.014044098     0.016179818  0.011982914
ITEM.PURCHASED          0.493024184  0.014553589     0.022297922  0.011719635
CATEGORY                1.000000000 -0.009137523     0.001466888  0.013898561
PURCHASE.AMOUNT        -0.009137523  1.000000000     0.015880736  0.019765879
LOCATION                0.001466888  0.015880736     1.000000000  0.014324087
SIZE                    0.013898561  0.019765879     0.014324087  1.000000000
COLOR                   0.030885758 -0.017646738    -0.021147572 -0.012425287
SEASON                  0.024791782  0.015717864     0.048918472 -0.001055839
REVIEW.RATE             0.025051585  0.030775923     0.009275515 -0.004124729
SUBSCRIPTIONS          -0.006116087  0.006996041     0.025651650  0.011666577
SHIPPING.TYPE           0.013916451 -0.004691885     0.016207264 -0.008475597
DISCOUNT.APPLIED       -0.015846604  0.017798055     0.009819277  0.016469896
PROMO_CODE_USED        -0.015846604  0.017798055     0.009819277  0.016469896
PREVIOUS.PURCHASES      0.014390517  0.008063412     0.004228303 -0.005101483
PAYMENT.METHOD         -0.014297639  0.018268281    -0.026079625 -0.010823916
FREQUENCY.OF.PURCHASES -0.013978233  0.012782056     0.010243644 -0.033007943
                       COLOR        SEASON       REVIEW.RATE  SUBSCRIPTIONS
CUSTOMER.ID             0.010546516  0.013730841  0.001343012  0.768960362 
AGE                    -0.019860983  0.019300493 -0.021949148 -0.006491647 
GENDER                  0.006721157  0.014328538 -0.008163790  0.417196816 
ITEM.PURCHASED          0.017113237  0.019270203  0.030357957  0.002254828 
CATEGORY                0.030885758  0.024791782  0.025051585 -0.006116087 
PURCHASE.AMOUNT        -0.017646738  0.015717864  0.030775923  0.006996041 
LOCATION               -0.021147572  0.048918472  0.009275515  0.025651650 
SIZE                   -0.012425287 -0.001055839 -0.004124729  0.011666577 
COLOR                   1.000000000  0.021034061 -0.027372981  0.016708773 
SEASON                  0.021034061  1.000000000 -0.020609336 -0.008696062 
REVIEW.RATE            -0.027372981 -0.020609336  1.000000000  0.006368054 
SUBSCRIPTIONS           0.016708773 -0.008696062  0.006368054  1.000000000 
SHIPPING.TYPE           0.037436323 -0.012341394 -0.008341976  0.005608806 
DISCOUNT.APPLI

In [7]:
# DROP CUSTOMER ID #

# Specify the column to be removed
col_to_remove <- "CUSTOMER.ID"

# Remove the specified column
df <- df[, !(colnames(df) %in% col_to_remove), drop = FALSE]

# Display the modified data frame
head(df)

AGE GENDER ITEM.PURCHASED CATEGORY PURCHASE.AMOUNT LOCATION SIZE COLOR SEASON
1 55  0      0              0        53              0        0    0     0     
2 19  0      1              0        64              1        0    1     0     
3 50  0      2              0        73              2        1    1     1     
4 21  0      3              1        90              3        2    1     1     
5 45  0      0              0        49              4        2    2     1     
6 46  0      4              1        20              5        2    3     2     
  REVIEW.RATE SUBSCRIPTIONS SHIPPING.TYPE DISCOUNT.APPLIED PROMO_CODE_USED
1 3.1         0             0             0                0              
2 3.1         0             0             0                0              
3 3.1         0             1             0                0              
4 3.5         0             2             0                0              
5 2.7         0             1             0                0              
6 2.9         0             3             0                0              
  PREVIOUS.PURCHASES PAYMENT.METHOD FREQUENCY.OF.PURCHASES
1 14                 0              0                     
2  2                 1              0                     
3 23                 2              1                     
4 49                 3              1                     
5 31                 3              2                     
6 14                 0              1

In [8]:
cor_matrix <- cor(df)
cor_matrix

AGE          GENDER       ITEM.PURCHASED CATEGORY    
AGE                     1.000000000 -0.002763261  0.003797920    0.012336349
GENDER                 -0.002763261  1.000000000 -0.009858613   -0.005205720
ITEM.PURCHASED          0.003797920 -0.009858613  1.000000000    0.493024184
CATEGORY                0.012336349 -0.005205720  0.493024184    1.000000000
PURCHASE.AMOUNT        -0.010423647  0.014044098  0.014553589   -0.009137523
LOCATION                0.002397486  0.016179818  0.022297922    0.001466888
SIZE                   -0.021007726  0.011982914  0.011719635    0.013898561
COLOR                  -0.019860983  0.006721157  0.017113237    0.030885758
SEASON                  0.019300493  0.014328538  0.019270203    0.024791782
REVIEW.RATE            -0.021949148 -0.008163790  0.030357957    0.025051585
SUBSCRIPTIONS          -0.006491647  0.417196816  0.002254828   -0.006116087
SHIPPING.TYPE          -0.022290602 -0.010669697  0.005042345    0.013916451
DISCOUNT.APPLIED       -0.004366296  0.595823095 -0.007766058   -0.015846604
PROMO_CODE_USED        -0.004366296  0.595823095 -0.007766058   -0.015846604
PREVIOUS.PURCHASES      0.040444531 -0.035872605  0.005103386    0.014390517
PAYMENT.METHOD          0.001963116 -0.018432871  0.009739294   -0.014297639
FREQUENCY.OF.PURCHASES -0.013304658  0.015580428  0.001377600   -0.013978233
                       PURCHASE.AMOUNT LOCATION     SIZE         COLOR       
AGE                    -0.010423647     0.002397486 -0.021007726 -0.019860983
GENDER                  0.014044098     0.016179818  0.011982914  0.006721157
ITEM.PURCHASED          0.014553589     0.022297922  0.011719635  0.017113237
CATEGORY               -0.009137523     0.001466888  0.013898561  0.030885758
PURCHASE.AMOUNT         1.000000000     0.015880736  0.019765879 -0.017646738
LOCATION                0.015880736     1.000000000  0.014324087 -0.021147572
SIZE                    0.019765879     0.014324087  1.000000000 -0.012425287
COLOR                  -0.017646738    -0.021147572 -0.012425287  1.000000000
SEASON                  0.015717864     0.048918472 -0.001055839  0.021034061
REVIEW.RATE             0.030775923     0.009275515 -0.004124729 -0.027372981
SUBSCRIPTIONS           0.006996041     0.025651650  0.011666577  0.016708773
SHIPPING.TYPE          -0.004691885     0.016207264 -0.008475597  0.037436323
DISCOUNT.APPLIED        0.017798055     0.009819277  0.016469896  0.012177965
PROMO_CODE_USED         0.017798055     0.009819277  0.016469896  0.012177965
PREVIOUS.PURCHASES      0.008063412     0.004228303 -0.005101483 -0.031819831
PAYMENT.METHOD          0.018268281    -0.026079625 -0.010823916  0.016825976
FREQUENCY.OF.PURCHASES  0.012782056     0.010243644 -0.033007943 -0.001120297
                       SEASON       REVIEW.RATE  SUBSCRIPTIONS SHIPPING.TYPE
AGE                     0.019300493 -0.021949148 -0.006491647  -0.022290602 
GENDER                  0.014328538 -0.008163790  0.417196816  -0.010669697 
ITEM.PURCHASED          0.019270203  0.030357957  0.002254828   0.005042345 
CATEGORY                0.024791782  0.025051585 -0.006116087   0.013916451 
PURCHASE.AMOUNT         0.015717864  0.030775923  0.006996041  -0.004691885 
LOCATION                0.048918472  0.009275515  0.025651650   0.016207264 
SIZE                   -0.001055839 -0.004124729  0.011666577  -0.008475597 
COLOR                   0.021034061 -0.027372981  0.016708773   0.037436323 
SEASON                  1.000000000 -0.020609336 -0.008696062  -0.012341394 
REVIEW.RATE            -0.020609336  1.000000000  0.006368054  -0.008341976 
SUBSCRIPTIONS          -0.008696062  0.006368054  1.000000000   0.005608806 
SHIPPING.TYPE          -0.012341394 -0.008341976  0.005608806   1.000000000 
DISCOUNT.APPLIED        0.014659871  0.012485694  0.700202492  -0.000264082 
PROMO_CODE_USED         0.014659871  0.012485694  0.700202492  -0.000264082 
PREVIOUS.PURCHASES     -0.019732959  0.004229099 -0.030859436   0.007014237 
P

PURCHASE AMOUNT IS DEPENDENT AND OUR OTHER FEATURES ARE INDEPENDENT VARIABLE

In [9]:
## DECIDING FOR DEPENDENT AND INDEPENDENT VARIABLES
output <- df$PURCHASE.AMOUNT

# QUESTION 1 - A

Question: Train the model using 80% of this dataset and suggest an appropriate GLM to model ouput to input variables.  

Solution: PURCHASE.AMOUNT is Output which is continuous, and other variables are input, therefore Gaussian distribution is used. 80% of dataset is trained, 20% of dataset is tested by using Gaussian distribution.

In [10]:
data=df
model=glm(PURCHASE.AMOUNT~., family='gaussian', data=df)
coef(model)
summary(model)
#split the dataset
set.seed(32)
n=nrow(data)
indexes = sample(n,n*(80/100)) # the ratio of trainset is 80% and testset is 20%
trainset = data[indexes,]
testset = data[-indexes,]
# fit the model on the trainset
model_trained=glm(PURCHASE.AMOUNT~., family='gaussian', data=trainset)
# predict using the testset
pred=predict(model_trained,testset)

(Intercept)                    AGE                 GENDER 
           53.54844205            -0.01577424             0.32725079 
        ITEM.PURCHASED               CATEGORY               LOCATION 
            0.07749777            -0.37498989             0.02322081 
                  SIZE                  COLOR                 SEASON 
            0.46577905            -0.05471932             0.34243099 
           REVIEW.RATE          SUBSCRIPTIONS          SHIPPING.TYPE 
            0.99660161            -0.54090290            -0.05109976 
      DISCOUNT.APPLIED        PROMO_CODE_USED     PREVIOUS.PURCHASES 
            0.96536781                     NA             0.01484873 
        PAYMENT.METHOD FREQUENCY.OF.PURCHASES 
            0.27125409             0.15496580


Call:
glm(formula = PURCHASE.AMOUNT ~ ., family = "gaussian", data = df)

Coefficients: (1 not defined because of singularities)
                       Estimate Std. Error t value Pr(>|t|)    
(Intercept)            53.54844    2.99141  17.901   <2e-16 ***
AGE                    -0.01577    0.02500  -0.631   0.5280    
GENDER                  0.32725    1.01364   0.323   0.7468    
ITEM.PURCHASED          0.07750    0.06110   1.268   0.2048    
CATEGORY               -0.37499    0.33239  -1.128   0.2593    
LOCATION                0.02322    0.02652   0.875   0.3814    
SIZE                    0.46578    0.37981   1.226   0.2201    
COLOR                  -0.05472    0.05301  -1.032   0.3020    
SEASON                  0.34243    0.34057   1.005   0.3147    
REVIEW.RATE             0.99660    0.53062   1.878   0.0604 .  
SUBSCRIPTIONS          -0.54090    1.19847  -0.451   0.6518    
SHIPPING.TYPE          -0.05110    0.22263  -0.230   0.8185    
DISCOUNT.APPLIED        0.96537    1.2

# QUESTION 1 - B

  Question: Specify the significant variables on the output variable at the level of 𝛼=0.05 and explore the related hypotheses test. Estimate the parameters of your model

  Solution:
*   H0 : independence variables are not important
*   H1 : independence variables are important
*   if p.value < alpha H0 hypothesis is rejected
Intercept and Review.Rate p values are smaller than significance level(𝛼)=0.05, therefor H0 null hypothesis is rejected which means Intercept and Review.Rate are important. We should use it for our linear model.

In [11]:
#B

coef(model_trained) # estimate the parameters of model
summary(model_trained) # significant independent variables

(Intercept)                    AGE                 GENDER 
          51.289394305           -0.004485317            0.654112183 
        ITEM.PURCHASED               CATEGORY               LOCATION 
           0.078305802           -0.429708259            0.027995261 
                  SIZE                  COLOR                 SEASON 
           0.242657591           -0.014533448            0.091405897 
           REVIEW.RATE          SUBSCRIPTIONS          SHIPPING.TYPE 
           1.416518447           -0.031871677            0.004665501 
      DISCOUNT.APPLIED        PROMO_CODE_USED     PREVIOUS.PURCHASES 
           0.523050891                     NA            0.024836960 
        PAYMENT.METHOD FREQUENCY.OF.PURCHASES 
           0.229484658            0.065897774


Call:
glm(formula = PURCHASE.AMOUNT ~ ., family = "gaussian", data = trainset)

Coefficients: (1 not defined because of singularities)
                        Estimate Std. Error t value Pr(>|t|)    
(Intercept)            51.289394   3.337316  15.368   <2e-16 ***
AGE                    -0.004485   0.028061  -0.160    0.873    
GENDER                  0.654112   1.130930   0.578    0.563    
ITEM.PURCHASED          0.078306   0.068249   1.147    0.251    
CATEGORY               -0.429708   0.371184  -1.158    0.247    
LOCATION                0.027995   0.029600   0.946    0.344    
SIZE                    0.242658   0.425871   0.570    0.569    
COLOR                  -0.014533   0.059145  -0.246    0.806    
SEASON                  0.091406   0.382319   0.239    0.811    
REVIEW.RATE             1.416518   0.598729   2.366    0.018 *  
SUBSCRIPTIONS          -0.031872   1.343433  -0.024    0.981    
SHIPPING.TYPE           0.004666   0.248994   0.019    0.985    
DISCOUNT.APPLIED   

# QUESTION 1 - C

Question : Predict the output of the test dataset using the trained model. Provide the functional form of the optimal predictive model.

Solution: ŷ = 51.289394 + 1.416518 * REVIEW.RATE
*   ŷ is output which is PURCHASE.AMOUNT, and it will be predicted by using 51.289394 + 1.416518 * REVIEW.RATE linear model
*   51.289394 is Intercept which means β0   
*   1.416518 is important input estimated value which is β1

ŷ values will change based on REVIEW.RATE which mean is if REVIEW.RATE value will increase ŷ will increase because of positive estimated value of REVIEW.RATE(+ 1.416518).

In [12]:
# predictive model pred.PURCHASE.AMOUNT y = 51.289394 + 1.416518 * REVIEW.RATE

# we use just REVIEW RATE becuase it's p. value is lower than alpha = 0.05 which means it is significant value for PURCHASEA.AMONUT
        ## which is our target or dependent

# QUESTION 1 - D

Question: Provide the confusion matrix and obtain the probability of correctness of predictions.

Solution: After having solution of accuracy we will have accuracy result as "0.00128205128205128" which means our input variables do not explain target variable well. We need to use different input variables to explain our target varaible.

In [13]:
# predict using the testset
actual = testset$PURCHASE.AMOUNT
confusion_matrix=table(pred,actual)
head(confusion_matrix)

accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
print(paste("Accuracy : ",accuracy))

                  actual
pred               20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
  55.914792397374   1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.0794831466412  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.1797996454242  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.2445866103897  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.3459435950608  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.4242368460454  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
                  actual
pred               40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
  55.914792397374   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.0794831466412  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.1797996454242  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  56.2445866103897  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
  

[1] "Accuracy :  0.00128205128205128"


# QUESTION 2 is PDF format it will be in zip folder

# QUESTION 3

In [14]:
df_stock <- read.csv("ADANIPORTS.csv")
head(df_stock)

Date       Symbol     Series Prev.Close Open   High    Low Last Close  
1 2007-11-27 MUNDRAPORT EQ     440.00     770.00 1050.00 770  959  962.90
2 2007-11-28 MUNDRAPORT EQ     962.90     984.00  990.00 874  885  893.90
3 2007-11-29 MUNDRAPORT EQ     893.90     909.00  914.75 841  887  884.20
4 2007-11-30 MUNDRAPORT EQ     884.20     890.00  958.00 890  929  921.55
5 2007-12-03 MUNDRAPORT EQ     921.55     939.75  995.00 922  980  969.30
6 2007-12-04 MUNDRAPORT EQ     969.30     985.00 1056.00 976 1049 1041.45
  VWAP    Volume   Turnover     Trades Deliverable.Volume X.Deliverble
1  984.72 27294366 2.687719e+15 NA     9859619            0.3612      
2  941.38  4581338 4.312765e+14 NA     1453278            0.3172      
3  888.09  5124121 4.550658e+14 NA     1069678            0.2088      
4  929.17  4609762 4.283257e+14 NA     1260913            0.2735      
5  965.65  2977470 2.875200e+14 NA      816123            0.2741      
6 1015.39  4849250 4.923867e+14 NA     1537667            0.3171

In [ ]:
install.packages("tseries")
install.packages("forecast")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘xts’, ‘TTR’, ‘quadprog’, ‘zoo’, ‘quantmod’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘fracdiff’, ‘lmtest’, ‘Rcpp’, ‘timeDate’, ‘urca’, ‘RcppArmadillo’




In [ ]:
library(forecast)
library(tseries)

# QUESTION 3

In [ ]:
df_stock_prev_close <- df_stock$Prev.Close
df_stock_open <- df_stock$Open
# Create time series object
ts_stock_open <- ts(df_stock_open, frequency = 1)
# Plot time series
plot(ts_stock_open, main = "Time Series Plot - Open Prices", xlab = "Time", ylab = "Open Prices")
# Print the time series
print(ts_stock_open)
# Check the class
class(ts_stock_open)

# QUESTION 3-A

Question: Check whether the time series is stationary in mean and variance.

Solution: To check wheter the time series is stationary in mean and variance, Dickey-Fuller test is used to assess whether a time series is stationary by examining the presence of a unit root, which is related to changes in mean and variance over time. If the test suggests the absence of a unit root, it implies that the time series is stationary in both mean and variance. We can see with the our p value result is lower than our significance level(𝛼)=0.05, so we can say our mean and variance for the time series are stationary.

In [ ]:
adf.test(ts_stock_open, alternative = "stationary") #Dickey-Fuller Test

stationary_mean = diff(ts_stock_open)
plot(stationary_mean)

stationary_variance = log(ts_stock_open)
diff_stationary_variance = diff(stationary_variance)
plot(diff_stationary_variance)

# QUESTION 3-B

Question: Use acf() and pacf() functions to identify the order of AR and MA

Solution: The AR component refers to the autoregressive part of the model. It involves regressing the current value of the time series against its previous values. The MA component refers to the moving average part of the model. It involves modeling the error term as a linear combination of past error terms, acf() is used to compute for AR, and pacf() is used to compute for MA. When we move away from lag 0 and examine autocorrelations at larger lags, the height of the ACF bars indicates the strength of the correlation between the time series values at the given lag, the ACF at lag 0 is always 1 because any time series is perfectly correlated with itself at the same time point. MA(1) means that the current value of the time series is influenced by the most recent past white noise term, and only that term. The "1" in MA(1) indicates the number of lags of the white noise term that are included in the model.

In [ ]:
acf( ts_stock_open , lag.max=50)
pacf( ts_stock_open , lag.max=50)

# QUESTION 3-C

Question: Use auto.arima() to learn the best ARIMA model.

Solution: The notation ARIMA(p, d, q) is used to describe a specific model.
*   p (order of AutoRegressive component): This represents the number of autoregressive (AR) terms in the model. AR terms are lagged values of the time series.
*   d (degree of differencing): This is the number of times the raw observations are differenced. Differencing is a method used to make the time series stationary. If d is 1, it means the series is differenced once.
*   q (order of Moving Average component): This represents the number of moving average (MA) terms in the model. MA terms are lagged forecast errors in prediction equations.

*   AR(2): It includes two autoregressive terms.
*   I(1): It includes one differencing to make the series stationary.
*   MA(2): It includes two moving average terms.

In [ ]:
auto.fit<-auto.arima(ts_stock_open, seasonal=F)  # automatic way to find the optimized model
tsdisplay(residuals(auto.fit), lag.max=45)
summary(auto.fit)

# QUESTION 3-D

Question: Forecast h=10 step ahead prediction of the time series variable and plot it with the original time series.

In [ ]:
auto.fcast <- forecast(auto.fit, h=10)
plot(auto.fcast)